Deploy to heroku button
tableau/TabPy pull request #459
Opened 2020-10-07 04:40 UTC by ChairmanMa0

This adds a button to the Readme that deploys TabPy to the user's Heroku account.

2020-10-07 16:56 UTC, 0golovatyi approved these changes

2020-10-07 17:00 UTC, 0golovatyi commented
I deployed with the button and the app doesn't work

2020-10-07 18:22 UTC, 0golovatyi requested changes
After deploying with the button the app doesn't work and can't be reached.

2020-10-07 18:55 UTC, nmannheimer approved these changes

2020-10-08 22:48 UTC, ChairmanMa0 commented
Fixed the issue with the Procfile.
Verified the fix using:
https://heroku.com/deploy?template=https://github.com/tableau/TabPy/tree/deploy-to-heroku-button
This PR can't be tested using the button because it always deploys from master (which of course doesn't have the other changes yet).

2020-10-08 23:42 UTC, merged